# Generated by Django 4.0.8 on 2022-10-06 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='content',
        ),
    ]
